const { REPO_ROOT, DATA_DIR } = require('./paths');
const dispatchOptions = require('./dispatch-options');
const runtimes = require('./runtimes');

module.exports = {
  REPO_ROOT,
  DATA_DIR,
  discoverAgents: require('./discover'),
  parseAgentMd: require('./parse-agent-md'),
  serializeAgentMd: require('./serialize-agent-md'),
  extractResult: require('./extract-result'),
  validateArgs: require('./validate-args'),
  runCommands: require('./run-commands'),
  renderTemplate: require('./render-template'),
  buildCommand: require('./build-command'),
  prepareAgent: require('./prepare-agent'),
  RunManager: require('./run-manager'),
  resolveAgentsDir: require('./resolve-agents-dir'),
  resolveWorkspaceDir: require('./resolve-workspace-dir'),
  resolveLogsDir: require('./resolve-logs-dir'),
  resolveCwd: require('./resolve-cwd'),
  createRunLogger: require('./run-logger'),
  createWorktree: require('./worktree').createWorktree,
  removeWorktree: require('./worktree').removeWorktree,
  Scheduler: require('./scheduler'),
  DEFAULT_TIMEOUT_SEC: dispatchOptions.DEFAULT_TIMEOUT_SEC,
  DISPATCH_OPTIONS: dispatchOptions.DISPATCH_OPTIONS,
  DISPATCH_OPTION_KEYS: dispatchOptions.DISPATCH_OPTION_KEYS,
  validateDispatchOptions: dispatchOptions.validateDispatchOptions,
  pickDispatchOptions: dispatchOptions.pickDispatchOptions,
  getRuntime: runtimes.getRuntime,
  listRuntimes: runtimes.listRuntimes,
  listRuntimeMetadata: runtimes.listRuntimeMetadata,
  isValidRuntime: runtimes.isValidRuntime,
  normalizeRuntimeOptions: runtimes.normalizeRuntimeOptions,
};
